# Generated by Django 4.2 on 2023-04-22 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0004_review"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Review",
            new_name="Reviews",
        ),
    ]
